import subprocess,os
os.chdir(r"c:\Users\charl\Documents\Flare")
print('staged diff:')
print(subprocess.run(['git','diff','--staged'],capture_output=True,text=True).stdout)
print('status:')
print(subprocess.run(['git','status','-s'],capture_output=True,text=True).stdout)
print('adding header and committing')
print(subprocess.run(['git','add','flare/sources/include/toonz/mypaintbrushstyle.h'],capture_output=True,text=True).stdout)
print(subprocess.run(['git','commit','-m','fix(mypaint): include <map> in header to fix build','--no-verify'],capture_output=True,text=True).stdout)
print('after commit status:')
print(subprocess.run(['git','status','-s'],capture_output=True,text=True).stdout)
print('pushing to origin')
push= subprocess.run(['git','push','origin','B4uti4github-patch-1'],capture_output=True,text=True)
print(push.stdout)
print(push.stderr)
print('aborting any rebase')
print(subprocess.run(['git','rebase','--abort'],capture_output=True,text=True).stdout)
print(subprocess.run(['git','rebase','--abort'],capture_output=True,text=True).stderr)
